//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:6.0.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPrototyper.NET.Standard.v20.CosmosDb.Templates {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class AzureCosmosDbContextTemplate : AzureCosmosDbContextTemplateBase {
        
        
        private CloudPrototyper.NET.Standard.v20.CosmosDb.Generators.AzureCosmosDbContextGenerator _ModelField;
        
        public CloudPrototyper.NET.Standard.v20.CosmosDb.Generators.AzureCosmosDbContextGenerator Model {
            get {
                return this._ModelField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 7 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("using Microsoft.Azure.Cosmos;\r\nusing System.Collections.Generic;\r\nusing System.Li" +
                    "nq;\r\n\r\nnamespace ");
            
            #line default
            #line hidden
            
            #line 11 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Namespace ));
            
            #line default
            #line hidden
            
            #line 11 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" \r\n{\r\n    public class ");
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Name ));
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" : ");
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.StorageInterface.Namespace ));
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.StorageInterface.Name ));
            
            #line default
            #line hidden
            
            #line 13 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\r\n    {\r\n");
            
            #line default
            #line hidden
            
            #line 15 "Templates\AzureCosmosDbContextTemplate.tt"
 if (Model.ModelParameters.UseGateway) { 
            
            #line default
            #line hidden
            
            #line 16 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\tprivate static CosmosClientOptions options = new CosmosClientOptions() { Connec" +
                    "tionMode = ConnectionMode.Gateway };\r\n\t\tprivate static CosmosClient _client  = n" +
                    "ew CosmosClient(\"");
            
            #line default
            #line hidden
            
            #line 17 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.ModelParameters.ConnectionString ));
            
            #line default
            #line hidden
            
            #line 17 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\", options);\r\n");
            
            #line default
            #line hidden
            
            #line 18 "Templates\AzureCosmosDbContextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 19 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("        private static CosmosClient _client  = new CosmosClient(\"");
            
            #line default
            #line hidden
            
            #line 19 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.ModelParameters.ConnectionString ));
            
            #line default
            #line hidden
            
            #line 19 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\");\r\n");
            
            #line default
            #line hidden
            
            #line 20 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 21 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("        private readonly Container _container;\r\n\t\t\r\n        public ");
            
            #line default
            #line hidden
            
            #line 23 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Name ));
            
            #line default
            #line hidden
            
            #line 23 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("() \r\n\t\t{\r\n            _container = _client.GetContainer(\"");
            
            #line default
            #line hidden
            
            #line 25 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.ModelParameters.DatabaseName ));
            
            #line default
            #line hidden
            
            #line 25 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\", \"");
            
            #line default
            #line hidden
            
            #line 25 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.ModelParameters.Name ));
            
            #line default
            #line hidden
            
            #line 25 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\");\r\n\t\t}\r\n\t\t\r\n        public string GetName()\r\n        {\r\n            return \"");
            
            #line default
            #line hidden
            
            #line 30 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Key ));
            
            #line default
            #line hidden
            
            #line 30 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\";\r\n        }\r\n\t\t\r\n\t\tpublic List<object> GetEntities(string entitySetName, string" +
                    " entityName, ");
            
            #line default
            #line hidden
            
            #line 33 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Query.Namespace ));
            
            #line default
            #line hidden
            
            #line 33 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 33 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.Query.Name ));
            
            #line default
            #line hidden
            
            #line 33 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" query)\r\n\t\t{\r\n\t\t\tif(query.IsNominal) \r\n\t\t\t{\r\n");
            
            #line default
            #line hidden
            
            #line 37 "Templates\AzureCosmosDbContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            
            #line 38 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\tif(entityName == \"");
            
            #line default
            #line hidden
            
            #line 38 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 38 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\")\r\n\t\t\t\t{\r\n\t\t\t\t\tif(query.PropertyName == \"Id\")\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tvar id = query.Nomi" +
                    "nalParameter.PadLeft(9, \'0\');\r\n\t\t\t\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 43 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 43 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 43 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 43 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.CosmosId.CompareTo(id) == 0).ToList().Cast<object>().ToList(" +
                    ");\r\n\t\t\t\t\t}\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 46 "Templates\AzureCosmosDbContextTemplate.tt"
 foreach(var prop in entity.ModelParameters.Properties.Where(x=>x.Name != "Id")) { 
            
            #line default
            #line hidden
            
            #line 47 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\tif(query.PropertyName == \"");
            
            #line default
            #line hidden
            
            #line 47 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 47 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\") \r\n\t\t\t\t\t{\r\n");
            
            #line default
            #line hidden
            
            #line 49 "Templates\AzureCosmosDbContextTemplate.tt"
 if (prop.Type == "System.String") { 
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.");
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 50 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".CompareTo(query.NominalParameter) == 0).ToList().Cast<object>().ToList();\r\n");
            
            #line default
            #line hidden
            
            #line 51 "Templates\AzureCosmosDbContextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 52 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t\tvar param = ");
            
            #line default
            #line hidden
            
            #line 52 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Type ));
            
            #line default
            #line hidden
            
            #line 52 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".Parse(query.NominalParameter);\r\n\t\t\t\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.");
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 53 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" == param).ToList().Cast<object>().ToList();\r\n");
            
            #line default
            #line hidden
            
            #line 54 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 55 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t}\r\n");
            
            #line default
            #line hidden
            
            #line 56 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 57 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t}\t \r\n");
            
            #line default
            #line hidden
            
            #line 58 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 59 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t}\r\n\t\t\telse \r\n\t\t\t{\r\n");
            
            #line default
            #line hidden
            
            #line 62 "Templates\AzureCosmosDbContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            
            #line 63 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\tif(entityName == \"");
            
            #line default
            #line hidden
            
            #line 63 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 63 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\")\r\n\t\t\t\t{\r\n\t\t\t\t\tif(query.PropertyName == \"Id\")\r\n\t\t\t\t\t{\r\n\t\t\t\t\t\tvar minId = query.M" +
                    "inValue.PadLeft(9, \'0\');\r\n\t\t\t\t\t\tvar maxId = query.MaxValue.PadLeft(9, \'0\');\r\n\t\t\t" +
                    "\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 69 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 69 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 69 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 69 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.CosmosId.CompareTo(minId) >= 0 && e.CosmosId.CompareTo(maxId" +
                    ") <= 0).ToList().Cast<object>().ToList();\r\n\t\t\t\t\t}\r\n\r\n");
            
            #line default
            #line hidden
            
            #line 72 "Templates\AzureCosmosDbContextTemplate.tt"
 foreach(var prop in entity.ModelParameters.Properties.Where(x=>x.Name != "Id")) { 
            
            #line default
            #line hidden
            
            #line 73 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\tif(query.PropertyName == \"");
            
            #line default
            #line hidden
            
            #line 73 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 73 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\") \r\n\t\t\t\t\t{\r\n");
            
            #line default
            #line hidden
            
            #line 75 "Templates\AzureCosmosDbContextTemplate.tt"
 if (prop.Type == "System.String") { 
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.");
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".CompareTo(query.MinValue) >= 0 && e.");
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 76 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".CompareTo(query.MaxValue) <= 0).ToList().Cast<object>().ToList();\r\n");
            
            #line default
            #line hidden
            
            #line 77 "Templates\AzureCosmosDbContextTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            
            #line 78 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t\tvar minParam = ");
            
            #line default
            #line hidden
            
            #line 78 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Type ));
            
            #line default
            #line hidden
            
            #line 78 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".Parse(query.MinValue);\r\n\t\t\t\t\t\tvar maxParam = ");
            
            #line default
            #line hidden
            
            #line 79 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Type ));
            
            #line default
            #line hidden
            
            #line 79 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".Parse(query.MaxValue);\r\n\t\t\t\t\t\treturn _container.GetItemLinqQueryable<");
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Namespace ));
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(true).Where(e => e.");
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" >= minParam && e.");
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( prop.Name ));
            
            #line default
            #line hidden
            
            #line 80 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(" <= maxParam).ToList().Cast<object>().ToList();\r\n");
            
            #line default
            #line hidden
            
            #line 81 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 82 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t\t}\r\n");
            
            #line default
            #line hidden
            
            #line 83 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 84 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\t\t}\t \r\n");
            
            #line default
            #line hidden
            
            #line 85 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 86 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(@"			}
			
			return new List<object>();
		}


		public void InsertAll(string entitySetName, string entityName, object[] toInsert)
		{
            foreach (var obj in toInsert)
            {
                _container.CreateItemAsync(obj).Wait();
            }
		}

		public void Insert(string entitySetName,string entityName, int count)
		{
			object[] generated = null;
");
            
            #line default
            #line hidden
            
            #line 103 "Templates\AzureCosmosDbContextTemplate.tt"
 foreach(var entity in Model.Entities) { 
            
            #line default
            #line hidden
            
            #line 104 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\tif(entityName == \"");
            
            #line default
            #line hidden
            
            #line 104 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 104 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\")\r\n\t\t\t{\r\n\t\t\t\tgenerated = ");
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.DataGenerator.Namespace));
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( Model.DataGenerator.Name ));
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".GetInstance().Generate<");
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.Namespace));
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(".");
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( entity.Name ));
            
            #line default
            #line hidden
            
            #line 106 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write(">(count).ToArray();\r\n\r\n\t\t\t} \r\n");
            
            #line default
            #line hidden
            
            #line 109 "Templates\AzureCosmosDbContextTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 110 "Templates\AzureCosmosDbContextTemplate.tt"
            this.Write("\t\t\tInsertAll(entitySetName,entityName,generated);\r\n\r\n\t\t}\r\n    }\r\n}");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Model"))) {
                    object data = this.Session["Model"];
                    if (typeof(CloudPrototyper.NET.Standard.v20.CosmosDb.Generators.AzureCosmosDbContextGenerator).IsAssignableFrom(data.GetType())) {
                        this._ModelField = ((CloudPrototyper.NET.Standard.v20.CosmosDb.Generators.AzureCosmosDbContextGenerator)(data));
                    }
                    else {
                        this.Error("The type \'CloudPrototyper.NET.Standard.v20.CosmosDb.Generators.AzureCosmosDbConte" +
                                "xtGenerator\' of the parameter \'Model\' did not match the type passed to the templ" +
                                "ate");
                    }
                }
            }

        }
    }
    
    public class AzureCosmosDbContextTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
