//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudPrototyper.NET.Framework.v462.Common.Templates.SolutionTemplates.Assemblies.NuGets {
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using System;
    
    
    public partial class WebApiPackageConfigTemplate : WebApiPackageConfigTemplateBase {
        
        
        private CloudPrototyper.NET.Framework.v462.Common.Generators.SolutionGenerators.Packages.PackagesConfigGenerator _ModelField;
        
        public CloudPrototyper.NET.Framework.v462.Common.Generators.SolutionGenerators.Packages.PackagesConfigGenerator Model {
            get {
                return this._ModelField;
            }
        }

        
        public virtual string TransformText() {
            this.GenerationEnvironment = null;
            
            #line 7 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write(@"<packages>
  <package id=""Microsoft.AspNet.WebApi"" version=""5.2.3"" targetFramework=""net462"" />
  <package id=""Microsoft.AspNet.WebApi.Client"" version=""5.2.3"" targetFramework=""net462"" />
  <package id=""Microsoft.AspNet.WebApi.Core"" version=""5.2.3"" targetFramework=""net462"" />
  <package id=""Microsoft.AspNet.WebApi.WebHost"" version=""5.2.3"" targetFramework=""net462"" />
  <package id=""Microsoft.CodeDom.Providers.DotNetCompilerPlatform"" version=""1.0.0"" targetFramework=""net462"" />
  <package id=""Microsoft.Net.Compilers"" version=""1.0.0"" targetFramework=""net462"" developmentDependency=""true"" />
  <package id=""Newtonsoft.Json"" version=""6.0.4"" targetFramework=""net462"" />
  <package id=""MSBuild.Microsoft.VisualStudio.Web.targets"" version=""14.0.0.3"" targetFramework=""net462"" />
");
            
            #line default
            #line hidden
            
            #line 16 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
 foreach(var package in Model.Packages) { 
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write("  <package id=\"");
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( package.Id ));
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write("\" version=\"");
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( package.Version ));
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write("\" targetFramework=\"");
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture( package.Framework ));
            
            #line default
            #line hidden
            
            #line 17 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write("\" />\r\n");
            
            #line default
            #line hidden
            
            #line 18 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 19 "Templates\SolutionTemplates\Assemblies\NuGets\WebApiPackageConfigTemplate.tt"
            this.Write("</packages>");
            
            #line default
            #line hidden
            return this.GenerationEnvironment.ToString();
        }
        
        public virtual void Initialize() {
            if ((this.Errors.HasErrors == false)) {
                if (((this.Session != null) 
                            && this.Session.ContainsKey("Model"))) {
                    object data = this.Session["Model"];
                    if (typeof(CloudPrototyper.NET.Framework.v462.Common.Generators.SolutionGenerators.Packages.PackagesConfigGenerator).IsAssignableFrom(data.GetType())) {
                        this._ModelField = ((CloudPrototyper.NET.Framework.v462.Common.Generators.SolutionGenerators.Packages.PackagesConfigGenerator)(data));
                    }
                    else {
                        this.Error("The type \'CloudPrototyper.NET.Framework.v462.Common.Generators.SolutionGenerators" +
                                ".Packages.PackagesConfigGenerator\' of the parameter \'Model\' did not match the ty" +
                                "pe passed to the template");
                    }
                }
            }

        }
    }
    
    public class WebApiPackageConfigTemplateBase {
        
        private global::System.Text.StringBuilder builder;
        
        private global::System.Collections.Generic.IDictionary<string, object> session;
        
        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;
        
        private string currentIndent = string.Empty;
        
        private global::System.Collections.Generic.Stack<int> indents;
        
        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();
        
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session {
            get {
                return this.session;
            }
            set {
                this.session = value;
            }
        }
        
        public global::System.Text.StringBuilder GenerationEnvironment {
            get {
                if ((this.builder == null)) {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set {
                this.builder = value;
            }
        }
        
        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors {
            get {
                if ((this.errors == null)) {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }
        
        public string CurrentIndent {
            get {
                return this.currentIndent;
            }
        }
        
        private global::System.Collections.Generic.Stack<int> Indents {
            get {
                if ((this.indents == null)) {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }
        
        public ToStringInstanceHelper ToStringHelper {
            get {
                return this._toStringHelper;
            }
        }
        
        public void Error(string message) {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }
        
        public void Warning(string message) {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }
        
        public string PopIndent() {
            if ((this.Indents.Count == 0)) {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }
        
        public void PushIndent(string indent) {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }
        
        public void ClearIndent() {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }
        
        public void Write(string textToAppend) {
            this.GenerationEnvironment.Append(textToAppend);
        }
        
        public void Write(string format, params object[] args) {
            this.GenerationEnvironment.AppendFormat(format, args);
        }
        
        public void WriteLine(string textToAppend) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }
        
        public void WriteLine(string format, params object[] args) {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }
        
        public class ToStringInstanceHelper {
            
            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;
            
            public global::System.IFormatProvider FormatProvider {
                get {
                    return this.formatProvider;
                }
                set {
                    if ((value != null)) {
                        this.formatProvider = value;
                    }
                }
            }
            
            public string ToStringWithCulture(object objectToConvert) {
                if ((objectToConvert == null)) {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type)) {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                            iConvertibleType});
                if ((methInfo != null)) {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                                this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}
