//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:5.0.7
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace CloudPrototyper.NET.Framework.v462.Common.Templates.ApiLayerTemplates.Utils
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;



    public partial class WebApiContainerInstallerTemplate : WebApiContainerInstallerTemplateBase
    {


        private CloudPrototyper.NET.Framework.v462.Common.Generators.ApiLayerGenerators.Utils.WebApiContainerInstallerGenerator _ModelField;

        public CloudPrototyper.NET.Framework.v462.Common.Generators.ApiLayerGenerators.Utils.WebApiContainerInstallerGenerator Model
        {
            get
            {
                return this._ModelField;
            }
        }


        public virtual string TransformText()
        {
            this.GenerationEnvironment = null;

#line 7 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write("using System;\r\nusing System.Web.Http;\r\nusing Castle.MicroKernel.Registration;\r\nus" +
                    "ing Castle.MicroKernel.SubSystems.Configuration;\r\nusing Castle.Windsor;\r\n// Web " +
                    "api container\r\nnamespace ");

#line default
#line hidden

#line 13 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Namespace));

#line default
#line hidden

#line 13 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(" \r\n{\r\n    public class ");

#line default
#line hidden

#line 15 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));

#line default
#line hidden

#line 15 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(@"  : IWindsorInstaller
    {
        public void Install(IWindsorContainer container, IConfigurationStore store)
        {
            container.Register(
			
               Classes.FromThisAssembly()
                    .BasedOn<ApiController>()
                    .LifestyleTransient(),
                Classes.FromAssemblyContaining<");

#line default
#line hidden

#line 24 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.OperationInterface.Namespace));

#line default
#line hidden

#line 24 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 24 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.OperationInterface.Name));

#line default
#line hidden

#line 24 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .BasedOn<");

#line default
#line hidden

#line 25 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.OperationInterface.Namespace));

#line default
#line hidden

#line 25 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 25 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.OperationInterface.Name));

#line default
#line hidden

#line 25 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .LifestyleTransient(),\r\n                Classes.FromAsse" +
                    "mblyContaining<");

#line default
#line hidden

#line 27 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ActionBase.Namespace));

#line default
#line hidden

#line 27 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 27 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ActionBase.Name));

#line default
#line hidden

#line 27 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .BasedOn<");

#line default
#line hidden

#line 28 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ActionBase.Namespace));

#line default
#line hidden

#line 28 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 28 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.ActionBase.Name));

#line default
#line hidden

#line 28 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .WithService.AllInterfaces()\r\n                    .Lifes" +
                    "tyleTransient(),\r\n                Classes.FromAssemblyContaining<");

#line default
#line hidden

#line 31 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusInterface.Namespace));

#line default
#line hidden

#line 31 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 31 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusInterface.Name));

#line default
#line hidden

#line 31 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .BasedOn<");

#line default
#line hidden

#line 32 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusInterface.Namespace));

#line default
#line hidden

#line 32 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 32 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusInterface.Name));

#line default
#line hidden

#line 32 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .LifestyleTransient(),\r\n                Classes.FromAsse" +
                    "mblyContaining<");

#line default
#line hidden

#line 34 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Namespace));

#line default
#line hidden

#line 34 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 34 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Name));

#line default
#line hidden

#line 34 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .BasedOn<");

#line default
#line hidden

#line 35 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Namespace));

#line default
#line hidden

#line 35 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 35 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.StorageInterface.Name));

#line default
#line hidden

#line 35 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .LifestyleTransient(),\r\n                Classes.FromAsse" +
                    "mblyContaining<");

#line default
#line hidden

#line 37 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Namespace));

#line default
#line hidden

#line 37 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 37 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Name));

#line default
#line hidden

#line 37 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .BasedOn<");

#line default
#line hidden

#line 38 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Namespace));

#line default
#line hidden

#line 38 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(".");

#line default
#line hidden

#line 38 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.MessageBusHandlerInterface.Name));

#line default
#line hidden

#line 38 "c:\Users\PV\source\repos\paasarch-cloud-prototyper\src\CloudPrototyper.NET.Framework.v462.Common\Templates\ApiLayerTemplates\Utils/WebApiContainerInstallerTemplate.tt"
            this.Write(">()\r\n                    .LifestyleSingleton()\r\n                );\r\n        }\r\n  " +
                    "  }\r\n}");

#line default
#line hidden
            return this.GenerationEnvironment.ToString();
        }

        public virtual void Initialize()
        {
            if ((this.Errors.HasErrors == false))
            {
                if (((this.Session != null)
                            && this.Session.ContainsKey("Model")))
                {
                    object data = this.Session["Model"];
                    if (typeof(CloudPrototyper.NET.Framework.v462.Common.Generators.ApiLayerGenerators.Utils.WebApiContainerInstallerGenerator).IsAssignableFrom(data.GetType()))
                    {
                        this._ModelField = ((CloudPrototyper.NET.Framework.v462.Common.Generators.ApiLayerGenerators.Utils.WebApiContainerInstallerGenerator)(data));
                    }
                    else
                    {
                        this.Error("The type \'CloudPrototyper.NET.Framework.v462.Common.Generators.ApiLayerGenerators" +
                                ".Utils.WebApiContainerInstallerGenerator\' of the parameter \'Model\' did not match" +
                                " the type passed to the template");
                    }
                }
            }

        }
    }

    public class WebApiContainerInstallerTemplateBase
    {

        private global::System.Text.StringBuilder builder;

        private global::System.Collections.Generic.IDictionary<string, object> session;

        private global::System.CodeDom.Compiler.CompilerErrorCollection errors;

        private string currentIndent = string.Empty;

        private global::System.Collections.Generic.Stack<int> indents;

        private ToStringInstanceHelper _toStringHelper = new ToStringInstanceHelper();

        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.session;
            }
            set
            {
                this.session = value;
            }
        }

        public global::System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.builder == null))
                {
                    this.builder = new global::System.Text.StringBuilder();
                }
                return this.builder;
            }
            set
            {
                this.builder = value;
            }
        }

        protected global::System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errors == null))
                {
                    this.errors = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errors;
            }
        }

        public string CurrentIndent
        {
            get
            {
                return this.currentIndent;
            }
        }

        private global::System.Collections.Generic.Stack<int> Indents
        {
            get
            {
                if ((this.indents == null))
                {
                    this.indents = new global::System.Collections.Generic.Stack<int>();
                }
                return this.indents;
            }
        }

        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this._toStringHelper;
            }
        }

        public void Error(string message)
        {
            this.Errors.Add(new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message));
        }

        public void Warning(string message)
        {
            global::System.CodeDom.Compiler.CompilerError val = new global::System.CodeDom.Compiler.CompilerError(null, -1, -1, null, message);
            val.IsWarning = true;
            this.Errors.Add(val);
        }

        public string PopIndent()
        {
            if ((this.Indents.Count == 0))
            {
                return string.Empty;
            }
            int lastPos = (this.currentIndent.Length - this.Indents.Pop());
            string last = this.currentIndent.Substring(lastPos);
            this.currentIndent = this.currentIndent.Substring(0, lastPos);
            return last;
        }

        public void PushIndent(string indent)
        {
            this.Indents.Push(indent.Length);
            this.currentIndent = (this.currentIndent + indent);
        }

        public void ClearIndent()
        {
            this.currentIndent = string.Empty;
            this.Indents.Clear();
        }

        public void Write(string textToAppend)
        {
            this.GenerationEnvironment.Append(textToAppend);
        }

        public void Write(string format, params object[] args)
        {
            this.GenerationEnvironment.AppendFormat(format, args);
        }

        public void WriteLine(string textToAppend)
        {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendLine(textToAppend);
        }

        public void WriteLine(string format, params object[] args)
        {
            this.GenerationEnvironment.Append(this.currentIndent);
            this.GenerationEnvironment.AppendFormat(format, args);
            this.GenerationEnvironment.AppendLine();
        }

        public class ToStringInstanceHelper
        {

            private global::System.IFormatProvider formatProvider = global::System.Globalization.CultureInfo.InvariantCulture;

            public global::System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProvider;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProvider = value;
                    }
                }
            }

            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                global::System.Type type = objectToConvert.GetType();
                global::System.Type iConvertibleType = typeof(global::System.IConvertible);
                if (iConvertibleType.IsAssignableFrom(type))
                {
                    return ((global::System.IConvertible)(objectToConvert)).ToString(this.formatProvider);
                }
                global::System.Reflection.MethodInfo methInfo = type.GetMethod("ToString", new global::System.Type[] {
                        iConvertibleType});
                if ((methInfo != null))
                {
                    return ((string)(methInfo.Invoke(objectToConvert, new object[] {
                            this.formatProvider})));
                }
                return objectToConvert.ToString();
            }
        }
    }
}